@echo off
ren "ComfyUI .bat" "ComfyUI.bat"
ren "convert img.bat" "ConvertImage.bat"
ren "EXIF Desc.bat" "ExifDescription.bat"
ren "EXIF Desc+csv.bat" "ExifDescriptionCsv.bat"
ren "Get list link url youtube2.bat" "YoutubeListLinksV2.bat"
ren "get phu de.bat" "GetSubtitles.bat"
ren "lay link utube danh sach.bat" "YoutubePlaylistLinks.bat"
ren "Locfile.bat" "FilterFiles.bat"
ren "LocFile2.bat" "FilterFilesV2.bat"
ren "Resize_optional.bat" "ResizeImageOptional.bat"
ren "resize_WEBP.bat" "ResizeWebP.bat"
ren "Sort_Media_ByDate_Input_EXIF.bat" "SortMediaByDateExif.bat"
ren "Sort_Media_ByDate.bat" "SortMediaByDate.bat"
ren "unlockfolder.bat" "UnlockFolder.bat"
ren "utube-add_sub_vn.bat" "YoutubeAddVietSub.bat"
ren "vast ComfyUI git auto.bat" "ComfyUIVastGitAuto.bat"
ren "vast.bat" "Vast.bat"
ren "YOUTUBE PLAYLIST DOWNLOADER VN.bat" "YoutubePlaylistDownloaderVN.bat"
ren "yt_vi_menu.bat" "YoutubeVietMenu.bat"